---
- name: Test Playbook
  hosts: all
  become: yes
  tasks:
    - name: install package
      yum:
        name: httpd
        state: installed
      notify: start service

  handlers:
    - name: start service
      service:
        name: httpd
        state: started 
