---
- name: setup tomcat
  hosts: all
  become: yes
  tasks:

    - name: INSTALL JAVA ON REDHAT
      yum:
        name: java
        state: installed
      when: ansible_os_family == "RedHat"
    
    - name: install java on Debian
      apt:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: download tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.91/bin/apache-tomcat-8.5.91.tar.gz
        dest: /opt/

    - name: extract tar file
      unarchive:
        src: /opt/apache-tomcat-8.5.91.tar.gz
        dest: /opt/
        remote_src: yes

    - name: permissions
      file:
        path: /opt/apache-tomcat-8.5.91/bin/startup.sh
        mode: '0777'

    - name: start service
      shell: nohup ./startup.sh
      args:
        chdir: /opt/apache-tomcat-10.1.11/bin

